name: Android CI

on:
  push:
    branches:
      - release

jobs:
  build:
    name: Build Android App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Decode and Save google-services.json
        run: |
          echo "$GOOGLE_SERVICES_JSON" | base64 --decode > app/google-services.json
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew assembleRelease

      - name: Upload Proguard mapping
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: app/build/outputs/mapping/release

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Upload APK to Firebase App Distribution
        run: |
          firebase appdistribution:distribute app/build/outputs/apk/release/app-release.apk \
            --app ${{ secrets.APP_ID }} \
            --release-notes "Release test2" \
            --testers-file testers.txt \
            --token "${{ secrets.FIREBASE_RELEASE_TOKEN }}"
